version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./tennis_tournament:/var/www/html
      - ./tennis_tournament/database/database.sqlite:/var/www/html/database/database.sqlite
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:key
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
